# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@types/node-15.12.1" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "15.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-15.12.1.tgz";
        sha512 = "zyxJM8I1c9q5sRMtVF+zdd13Jt6RU4r4qfhTd7lQubyThvLfx6yYekWSQjGCGV2Tkecgxnlpl/DNlb6Hg+dmEw==";
      };
    };
    "@types/node-fetch-2.5.10" = {
      name = "_at_types_slash_node-fetch";
      packageName = "@types/node-fetch";
      version = "2.5.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node-fetch/-/node-fetch-2.5.10.tgz";
        sha512 = "IpkX0AasN44hgEad0gEF/V6EgR5n69VEqPEgnmoM8GsIGro3PowbWs4tR6IhxUTyPLpOn+fiGG6nrQhcmoCuIQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "chalk-4.1.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.1.tgz";
        sha512 = "diHzdDKxcU+bAsUboHLPEDQiw0qEe0qd7SYUn3HgcFlWgbDcfLGswOHYeGrHKzG9z6UYf01d9VFMfZxPM1xZSg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "form-data-3.0.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-3.0.1.tgz";
        sha512 = "RHkBKtLWUVwd7SqRIvCZMEvAMoGUp0XU+seQiZejj0COz3RI3hWP4sCv3gZWWLjJTd7rGwcsF5eKZGii0r/hbg==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "mime-db-1.48.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.48.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.48.0.tgz";
        sha512 = "FM3QwxV+TnZYQ2aRqhlKBMHxk10lTbMt3bBkMAp54ddrNeVSfcQYOOKuGuy3Ddrm38I04If834fOUSq1yzslJQ==";
      };
    };
    "mime-types-2.1.31" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.31.tgz";
        sha512 = "XGZnNzm3QvgKxa8dpzyhFTHmpP3l5YNusmne07VUOXxou9CqUqYa/HBy124RqtVh/O2pECas/MOcsDgpilPOPg==";
      };
    };
    "node-bin-setup-1.0.6" = {
      name = "node-bin-setup";
      packageName = "node-bin-setup";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-bin-setup/-/node-bin-setup-1.0.6.tgz";
        sha512 = "uPIxXNis1CRbv1DwqAxkgBk5NFV3s7cMN/Gf556jSw6jBvV7ca4F9lRL/8cALcZecRibeqU+5dFYqFFmzv5a0Q==";
      };
    };
    "node-fetch-2.6.1" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.1.tgz";
        sha512 = "V4aYg89jEoVRxRb2fJdAg8FHvI7cEyYdVAh94HH0UIK8oJxUfkjlDQN9RbMx+bEjP7+ggMiFRprSti032Oipxw==";
      };
    };
    "shq-1.0.2" = {
      name = "shq";
      packageName = "shq";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shq/-/shq-1.0.2.tgz";
        sha512 = "8AvNyHL75DHlkbLmzF7nzTzT2F0qEfSewwxHjH79Ww8S+hGpIZVlf8b0TcdOwv4HqIkOVBInu9n+wqhUSl9Wag==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
  };
in
{
  engines = nodeEnv.buildNodePackage {
    name = "engines";
    packageName = "engines";
    version = "0.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/engines/-/engines-0.4.0.tgz";
      sha1 = "aefd16e99762ea4f809c5c3aeac4c5b22f068a8c";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Template engine library with fast, synchronous rendering, based on consolidate.";
      homepage = "https://github.com/assemble/engines";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "node->=14.8.0" = nodeEnv.buildNodePackage {
    name = "node";
    packageName = "node";
    version = "16.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/node/-/node-16.1.0.tgz";
      sha512 = "VCdVc3JI7WrGFwaentjwZsL936Gbzvi4k4y8pqWvml/7JM98oVY9mCv/WvzpPHr2NyZHXCngTiIa0Y26xufNSA==";
    };
    dependencies = [
      sources."node-bin-setup-1.0.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "node";
      homepage = "https://github.com/aredridel/node-bin-gen#readme";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "npm->=6.0.0" = nodeEnv.buildNodePackage {
    name = "npm";
    packageName = "npm";
    version = "7.16.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/npm/-/npm-7.16.0.tgz";
      sha512 = "UUnKcjS7qFhZT90iZY/ZWz/jwF+rS0fIohDf41T6/SRXEqut0aav+1NkL6g6GqQGpIVBzpZc75BDfpq4PhfXBg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "a package manager for JavaScript";
      homepage = "https://docs.npmjs.com/";
      license = "Artistic-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  zx = nodeEnv.buildNodePackage {
    name = "zx";
    packageName = "zx";
    version = "1.14.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/zx/-/zx-1.14.1.tgz";
      sha512 = "M8U7SM8nVnko4vaeb4jp2+gwIyaJpnLNqkOurViML2WOsIn9M+bVHmuJxlVPHKHB6WkoZ3P/0FESLKwvJF4dtw==";
    };
    dependencies = [
      sources."@types/node-15.12.1"
      sources."@types/node-fetch-2.5.10"
      sources."ansi-styles-4.3.0"
      sources."asynckit-0.4.0"
      sources."chalk-4.1.1"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."combined-stream-1.0.8"
      sources."delayed-stream-1.0.0"
      sources."form-data-3.0.1"
      sources."has-flag-4.0.0"
      sources."isexe-2.0.0"
      sources."mime-db-1.48.0"
      sources."mime-types-2.1.31"
      sources."node-fetch-2.6.1"
      sources."shq-1.0.2"
      sources."supports-color-7.2.0"
      sources."which-2.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A tool for writing better scripts";
      homepage = "https://github.com/google/zx#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "zx-git://github.com/google/zx.git" = nodeEnv.buildNodePackage {
    name = "zx";
    packageName = "zx";
    version = "1.14.1";
    src = fetchgit {
      url = "git://github.com/google/zx.git";
      rev = "2dfb3488bfc82fe205fe2eb566ef7f37abcbdf55";
      sha256 = "9c52dbb565148cac15f5916a4034aaee6fba19ab9311cce3676b0a949cf68a9d";
    };
    dependencies = [
      sources."@types/node-15.12.1"
      sources."@types/node-fetch-2.5.10"
      sources."ansi-styles-4.3.0"
      sources."asynckit-0.4.0"
      sources."chalk-4.1.1"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."combined-stream-1.0.8"
      sources."delayed-stream-1.0.0"
      sources."form-data-3.0.1"
      sources."has-flag-4.0.0"
      sources."isexe-2.0.0"
      sources."mime-db-1.48.0"
      sources."mime-types-2.1.31"
      sources."node-fetch-2.6.1"
      sources."shq-1.0.2"
      sources."supports-color-7.2.0"
      sources."which-2.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A tool for writing better scripts";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
